name: Add Pull Request Reviewer

on:
  workflow_dispatch: {}
  issue_comment:
    types: [created]
    branches:
      - '**'

jobs:
  add_pull_request_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract username
        id: extract
        run: |
          regex_match=$(echo "${{ github.event.comment.body }}" | grep -oP '@([a-zA-Z0-9-_]+) [Rr]eview [Rr]equest' | cut -c 2- | cut -d ' ' -f1)
          mentioned_users=($regex_match)
          echo "mentioned_users=${mentioned_users[@]}" >> $GITHUB_OUTPUT
      - name: Check if user exists
        uses: actions/github-script@v6
        id: check_users
        with:
          script: |
            let mentioned_users = '${{ steps.extract.outputs.mentioned_users }}';
            mentioned_users = mentioned_users.split(' ');
            let available_users = [];
            const pull_request_author = '${{ github.event.issue.user.login }}';
            for (const username of mentioned_users) {
              if ( username !== pull_request_author ) {
                const response = await github.request('GET /users/{username}', {
                  username: username
                });
                if (response.status === 200) {
                  available_users.push(username)
                }
              }
            };
            return available_users;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add user as reviewer
        uses: actions/github-script@v6
        if: ${{ steps.check_users.outputs.result }} !== []
        with:
          script: |
            const available_users = ${{ steps.check_users.outputs.result }};
            const { issue, repository } = context.payload;
            const pull_number = issue.number;
            await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
              owner: 'dangngoctuan',
              repo: repository.name,
              pull_number: pull_number,
              reviewers: available_users
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
